# Generated by Django 6.0.2 on 2026-02-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('request_type', models.CharField(choices=[('RESTAURANT', 'Restaurante'), ('COMMERCE', 'Comercio')], max_length=20)),
                ('zone', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=160)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('whatsapp', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
