# Generated by Django 6.0.2 on 2026-02-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='created_business_slug',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='created_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='temp_password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
