# Generated by Django 6.0.2 on 2026-03-18 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accessrequest_created_business_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Celular')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nombre completo')),
                ('default_address', models.CharField(blank=True, max_length=220, verbose_name='Dirección principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
