# Generated by Django 6.0.2 on 2026-02-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='review_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='review_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
