# Generated by Django 6.0.2 on 2026-02-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_review_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Prueba 15 días'), ('BASIC', 'Plan Básico (PDF)'), ('STANDARD', 'Plan Estándar (Productos)'), ('PREMIUM', 'Plan Premium (Destacado)')], default='FREE', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='plan_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='business',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
