# Generated by Django 6.0.2 on 2026-02-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_plan_business_plan_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='grace_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
