# Generated by Django 6.0.2 on 2026-02-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_business_grace_ends_at_business_paid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='last_visited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='last_whatsapp_click_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='visits_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='whatsapp_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
