# Generated by Django 6.0.2 on 2026-02-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_last_visited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_accepting_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='business',
            name='schedule_fri',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='schedule_mon',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='schedule_sat',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='schedule_sun',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='schedule_thu',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='schedule_tue',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='schedule_wed',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='show_closed_in_list',
            field=models.BooleanField(default=False),
        ),
    ]
