# Generated by Django 6.0.2 on 2026-02-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_business_is_accepting_orders_business_schedule_fri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='map_embed_url',
            field=models.URLField(blank=True, default='', help_text='Opcional: enlace de insertar mapa (Compartir → Insertar un mapa)'),
        ),
        migrations.AddField(
            model_name='business',
            name='maps_url',
            field=models.URLField(blank=True, default='', help_text='Pega aquí el enlace de Google Maps (Compartir → Copiar enlace)'),
        ),
    ]
