# Generated by Django 6.0.2 on 2026-02-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_business_map_embed_url_business_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='promo_active',
            field=models.BooleanField(default=False, help_text='Activa/desactiva la promoción que se mostrará en el detalle del negocio.'),
        ),
        migrations.AddField(
            model_name='business',
            name='promo_text',
            field=models.TextField(blank=True, default='', help_text='Texto opcional de la promo. Ej: Válido hasta las 8pm'),
        ),
        migrations.AddField(
            model_name='business',
            name='promo_title',
            field=models.CharField(blank=True, default='', help_text='Título corto de la promo. Ej: 2x1 en hamburguesas', max_length=120),
        ),
    ]
