# Generated by Django 6.0.2 on 2026-03-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_business_promo_active_business_promo_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Foto de portada para el directorio (recomendado 1200x600).', null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='zone',
            field=models.CharField(blank=True, choices=[('SUR', 'Sur'), ('NORTE', 'Norte'), ('ORIENTE', 'Oriente'), ('CENTRO', 'Centro')], max_length=20, null=True),
        ),
    ]
