# Generated by Django 6.0.2 on 2026-03-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_business_cover_image_alter_business_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Palabras clave separadas por coma. Ej: pizza, hamburguesa, café, droguería', max_length=250),
        ),
    ]
