# Generated by Django 6.0.2 on 2026-03-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_business_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Separa por coma. Ej: pizza, hamburguesa, café, droguería, mercado', max_length=250, verbose_name='Etiquetas (tags)'),
        ),
    ]
