# Generated by Django 6.0.2 on 2026-03-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0011_alter_business_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='avg_prep_time',
            field=models.PositiveIntegerField(default=25, help_text='Tiempo promedio de preparación en minutos'),
        ),
    ]
