# Generated by Django 6.0.2 on 2026-03-25 00:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_business_avg_prep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo fijo del domicilio para este negocio', max_digits=10),
        ),
        migrations.AddField(
            model_name='business',
            name='nequi_number',
            field=models.CharField(blank=True, default='', help_text='Número Nequi donde el cliente debe transferir', max_length=20),
        ),
    ]
