# Generated by Django 6.0.2 on 2026-03-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0013_business_delivery_fee_business_nequi_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud del negocio', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud del negocio', max_digits=9, null=True),
        ),
    ]
