# Generated by Django 6.0.2 on 2026-03-26 00:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0014_business_latitude_business_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='service_mode',
            field=models.CharField(choices=[('DELIVERY', 'Solo domicilio'), ('PICKUP', 'Solo recoger en el punto'), ('BOTH', 'Domicilio y recoger en el punto')], default='BOTH', help_text='Define si el negocio vende por domicilio, recogida en punto o ambas opciones.', max_length=20, verbose_name='Modalidad de entrega'),
        ),
        migrations.AlterField(
            model_name='business',
            name='avg_prep_time',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='business',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='map_embed_url',
            field=models.URLField(blank=True, default='', help_text='Opcional: enlace de insertar mapa'),
        ),
        migrations.AlterField(
            model_name='business',
            name='nequi_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='promo_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='business',
            name='promo_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='promo_title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='business',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
