# Generated by Django 6.0.2 on 2026-03-26 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0015_business_service_mode_alter_business_avg_prep_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-created_at'], 'verbose_name': 'Negocio', 'verbose_name_plural': 'Negocios'},
        ),
    ]
