# Generated by Django 6.0.2 on 2026-03-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0017_alter_business_business_type_businessgallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='¿Tiene parqueadero?'),
        ),
        migrations.AddField(
            model_name='business',
            name='min_consumption',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Consumo mínimo'),
        ),
        migrations.AddField(
            model_name='business',
            name='music_type',
            field=models.CharField(blank=True, choices=[('SALSA', 'Salsa'), ('REGGAETON', 'Reggaetón'), ('CROSSOVER', 'Crossover'), ('POPULAR', 'Popular'), ('ELECTRONICA', 'Electrónica'), ('VALLENATO', 'Vallenato'), ('VARIADA', 'Variada')], default='', max_length=20, verbose_name='Tipo de música'),
        ),
        migrations.AddField(
            model_name='business',
            name='night_description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción Night'),
        ),
        migrations.AddField(
            model_name='business',
            name='reservation_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp reservas'),
        ),
    ]
