# Generated by Django 6.0.2 on 2026-03-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0018_business_has_parking_business_min_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='allow_table_booking',
            field=models.BooleanField(default=False, verbose_name='Permitir reservar mesa'),
        ),
        migrations.AddField(
            model_name='business',
            name='table_booking_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mensaje predeterminado para reserva'),
        ),
        migrations.AddField(
            model_name='business',
            name='table_booking_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp para reservas'),
        ),
    ]
