# Generated by Django 6.0.2 on 2026-03-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0019_business_allow_table_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='parking_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Costo del parqueadero'),
        ),
        migrations.AddField(
            model_name='business',
            name='parking_type',
            field=models.CharField(choices=[('NO', 'No tiene'), ('FREE', 'Gratis'), ('PAID', 'Pago')], default='NO', max_length=10, verbose_name='Parqueadero'),
        ),
    ]
