# Generated by Django 6.0.2 on 2026-03-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0020_business_parking_cost_business_parking_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businessrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='businessrating',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businessrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='business',
            name='allow_table_booking',
        ),
        migrations.RemoveField(
            model_name='business',
            name='has_parking',
        ),
        migrations.RemoveField(
            model_name='business',
            name='min_consumption',
        ),
        migrations.RemoveField(
            model_name='business',
            name='music_type',
        ),
        migrations.RemoveField(
            model_name='business',
            name='night_description',
        ),
        migrations.RemoveField(
            model_name='business',
            name='parking_cost',
        ),
        migrations.RemoveField(
            model_name='business',
            name='parking_type',
        ),
        migrations.RemoveField(
            model_name='business',
            name='reservation_phone',
        ),
        migrations.RemoveField(
            model_name='business',
            name='table_booking_message',
        ),
        migrations.RemoveField(
            model_name='business',
            name='table_booking_phone',
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurante'), ('COMMERCE', 'Comercio')], default='RESTAURANT', max_length=20),
        ),
        migrations.DeleteModel(
            name='BusinessGallery',
        ),
        migrations.DeleteModel(
            name='BusinessRating',
        ),
    ]
