# Generated by Django 6.0.2 on 2026-03-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0021_alter_businessrating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurante'), ('COMMERCE', 'Comercio'), ('NIGHT', 'Night')], default='RESTAURANT', max_length=20),
        ),
    ]
