# Generated by Django 6.0.2 on 2026-03-28 01:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0022_alter_business_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='allow_table_booking',
            field=models.BooleanField(default=False, verbose_name='Permitir reservar mesa'),
        ),
        migrations.AddField(
            model_name='business',
            name='min_consumption',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Consumo mínimo'),
        ),
        migrations.AddField(
            model_name='business',
            name='music_type',
            field=models.CharField(blank=True, choices=[('SALSA', 'Salsa'), ('REGGAETON', 'Reggaetón'), ('CROSSOVER', 'Crossover'), ('POPULAR', 'Popular'), ('ELECTRONICA', 'Electrónica'), ('VALLENATO', 'Vallenato'), ('VARIADA', 'Variada')], default='', max_length=20, verbose_name='Tipo de música'),
        ),
        migrations.AddField(
            model_name='business',
            name='night_description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción Night'),
        ),
        migrations.AddField(
            model_name='business',
            name='parking_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Costo del parqueadero'),
        ),
        migrations.AddField(
            model_name='business',
            name='parking_type',
            field=models.CharField(choices=[('NO', 'No tiene'), ('FREE', 'Gratis'), ('PAID', 'Pago')], default='NO', max_length=10, verbose_name='Parqueadero'),
        ),
        migrations.AddField(
            model_name='business',
            name='reservation_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp reservas'),
        ),
        migrations.AddField(
            model_name='business',
            name='table_booking_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mensaje predeterminado para reserva'),
        ),
        migrations.AddField(
            model_name='business',
            name='table_booking_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp para reservas'),
        ),
        migrations.CreateModel(
            name='BusinessGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='business_gallery/')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Foto de galería',
                'verbose_name_plural': 'Galería de fotos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-created_at'],
                'unique_together': {('business', 'user')},
            },
        ),
    ]
