# Generated by Django 6.0.2 on 2026-04-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0023_business_allow_table_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='night_category',
            field=models.CharField(blank=True, choices=[('BAR', 'Bar'), ('GASTROBAR', 'Gastrobar'), ('PUB', 'Pub'), ('KARAOKE', 'Karaoke'), ('DISCOTECA', 'Discoteca'), ('ROOFTOP', 'Rooftop')], default='', max_length=20, verbose_name='Tipo de negocio Night'),
        ),
    ]
