"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
from pathlib import Path


# =========================
# Base directory
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# SECURITY
# =========================
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-fallback-key-change-me"
)

DEBUG = os.environ.get("DJANGO_DEBUG", "0") == "1"

# Allowed hosts (Render)
allowed_hosts_env = os.environ.get("DJANGO_ALLOWED_HOSTS", "").strip()
if allowed_hosts_env:
    # ejemplo: ".onrender.com,tu-dominio.com"
    ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_env.split(",") if h.strip()]
else:
    # Para que no bloquee si no está configurado aún (puedes endurecer luego)
    ALLOWED_HOSTS = ["*"]

# CSRF trusted origins (Render)
csrf_env = os.environ.get("CSRF_TRUSTED_ORIGINS", "").strip()
if csrf_env:
    # ejemplo: "https://*.onrender.com,https://tu-dominio.com"
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in csrf_env.split(",") if o.strip()]
else:
    CSRF_TRUSTED_ORIGINS = ["https://*.onrender.com"]


# =========================
# Applications
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "businesses",
    "menu",
    "users",

    # django-storages (R2 / S3 compatible)
    "storages",
]


# =========================
# Middleware
# =========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # ✅ WhiteNoise para servir estáticos
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =========================
# URLs / WSGI
# =========================
ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"


# =========================
# Templates
# =========================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =========================
# Database
# =========================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 20,  # evita muchos "database is locked"
        },
    }
}


# =========================
# Password validation
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# =========================
# Internationalization
# =========================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/Bogota"
USE_I18N = True
USE_TZ = True


# =========================
# Static / Media
# =========================
STATIC_URL = "/static/"

# ✅ Para desarrollo/local: carpeta /static en el proyecto
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# ✅ OBLIGATORIO en Render para collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media local (si no usas R2)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# =========================
# Auth redirects
# =========================
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"


# =========================
# Default auto field
# =========================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =========================
# STORAGES (Django 6) - FIX del error 500
# =========================
# ✅ Deben existir "default" y "staticfiles"
STORAGES = {
    # Media/local por defecto (dev)
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": MEDIA_ROOT,
        },
    },
    # Estáticos con WhiteNoise
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# =========================
# R2 (Cloudflare) / S3 compatible
# =========================
# ✅ Por defecto OFF en local para no romper tu Windows
USE_R2 = os.environ.get("USE_R2", "0") == "1"

if USE_R2:
    AWS_ACCESS_KEY_ID = os.environ.get("R2_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.environ.get("R2_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("R2_BUCKET_NAME")
    AWS_S3_ENDPOINT_URL = os.environ.get("R2_ENDPOINT_URL")

    AWS_S3_REGION_NAME = "auto"
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_S3_ADDRESSING_STYLE = "virtual"  # suele funcionar bien en R2

    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False  # URLs limpias (sin firmas)
    AWS_S3_FILE_OVERWRITE = False

    # ✅ Cuando USE_R2=1, el storage por defecto (MEDIA) será R2
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    }

    # URL pública de tus archivos:
    MEDIA_URL = os.environ.get(
        "R2_PUBLIC_BASE_URL",
        f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"
    )
# ✅ Render/Django: asegurar STATIC_ROOT siempre (evita STATIC_ROOT=None)
STATIC_ROOT = BASE_DIR / "staticfiles"