# Generated by Django 6.0.2 on 2026-03-04 23:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0012_business_avg_prep_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer_name', models.CharField(max_length=120)),
                ('buyer_phone', models.CharField(max_length=40)),
                ('buyer_address', models.CharField(max_length=220)),
                ('buyer_notes', models.TextField(blank=True)),
                ('total', models.IntegerField(default=0)),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
            ],
        ),
    ]
