# Generated by Django 6.0.2 on 2026-03-12 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Celular')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Nombre')),
                ('successful_orders', models.PositiveIntegerField(default=0)),
                ('failed_orders', models.PositiveIntegerField(default=0)),
                ('is_blocked_cash', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Transferencia'), ('cash', 'Efectivo')], default='transfer', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('fake', 'Falso')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.customerprofile'),
        ),
    ]
