# Generated by Django 6.0.2 on 2026-03-18 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customerprofile_order_payment_method_order_status_and_more'),
        ('users', '0003_appcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='app_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.appcustomer'),
        ),
    ]
