# Generated by Django 6.0.2 on 2026-03-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_app_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('delivery', 'Domicilio'), ('pickup', 'Recoger en el punto')], default='delivery', max_length=20),
        ),
    ]
